# Generated by Django 6.0.3 on 2026-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_category_id_alter_community_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='dwelling_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('town_house', 'Town House'), ('granny_flat', 'Granny Flat'), ('room', 'Room')], default='unit', max_length=20),
        ),
    ]
