# Generated by Django 6.0.3 on 2026-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_dwelling_dwelling_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelling',
            name='dwelling_type',
            field=models.CharField(choices=[('house', 'House'), ('unit', 'Unit'), ('town_house', 'Town House'), ('granny_flat', 'Granny Flat'), ('room', 'Room')], default='unit', max_length=20),
        ),
    ]
